<refactor> cleaned up all command line messages. turned of verbose.

diff --git a/bin/cosm b/bin/cosm
--- a/bin/cosm
+++ b/bin/cosm
@@ -27,7 +27,7 @@ add(){
     if [ "$#" -eq 2 ]; then
         option="${2}"
         if [ "${option}" == "--latest" ]; then
-            lua $COSM_DIR/cli/cmd-add-latest.lua $PWD "${1}"
+            lua $COSM_DIR/cli/cmd-add-version.lua $PWD "${1}"
         elif [ "${option:0:1}" == "v" ]; then
             lua $COSM_DIR/cli/cmd-add-version.lua $PWD "${1}" "${option:1}"
         else
@@ -41,12 +41,19 @@ add(){
 }
 
 upgrade(){
-    if [ "$#" -eq 2 ]; then
-        option="${2}"
-        if [ "${option}" == "--latest" ]; then
-            lua $COSM_DIR/cli/cmd-upgrade-latest.lua $PWD "${1}"
-        elif [ "${option:0:1}" == "v" ]; then
-            lua $COSM_DIR/cli/cmd-upgrade-version.lua $PWD "${1}" "${option:1}"
+    if [ "$#" -eq 1 ]; then
+        if [ "${1}" == "--latest" ]; then
+            lua $COSM_DIR/cli/cmd-upgrade-all.lua $PWD "${@:2}"
+        else
+            printf "ArgumentError: the signature is 'cosm upgrade --latest'. See 'cosm --help'. \n \n"
+            exit 1
+        fi
+    elif [ "$#" -eq 2 ]; then
+        checkname $1
+        if [ "${2}" == "--latest" ]; then
+            lua $COSM_DIR/cli/cmd-upgrade-selection.lua $PWD "${1}"
+        elif [ "${2:0:1}" == "v" ]; then
+            lua $COSM_DIR/cli/cmd-upgrade-selection.lua $PWD "${1}" "${2:1}"
         else
             printf "ArgumentError: the signature is 'cosm upgrade <package name> [--latest, v<version>]'. See 'cosm --help'. \n \n"
             exit 1
@@ -221,7 +228,6 @@ case "$1" in
 
     # Evaluate in root directory of a package. Upgrade a project dependency with <name> to <version>
     upgrade)
-        checkname $2
         upgrade "${@:2}"
         ;;
 
