<cli> fixed interface for add, rm, upgrade and downgrade. Added tests. All tests passing.

diff --git a/cosm b/cosm
--- a/cosm
+++ b/cosm
@@ -72,45 +72,61 @@ init(){
 }
 
 add(){
-    case $2 in
-        --latest)
-            lua $COSM_DIR/cli/cmd-add-latest.lua $PWD "${1}" "${@:3}"
-            ;;
-        --version|-v)
-            lua $COSM_DIR/cli/cmd-add-version.lua $PWD "${1}" "${@:3}"
-            ;;
-        *)
-            printf "ArgumentError: the signature is 'cosm add <package name> [--latest, --version <version>]'. See 'cosm --help'. \n \n"
+    if [ "$#" -eq 2 ]; then
+        option="${2}"
+        if [ "${option}" == "--latest" ]; then
+            lua $COSM_DIR/cli/cmd-add-latest.lua $PWD "${1}"
+        elif [ "${option:0:1}" == "v" ]; then
+            lua $COSM_DIR/cli/cmd-add-version.lua $PWD "${1}" "${option:1}"
+        else
+            printf "ArgumentError: the signature is 'cosm upgrade <package name> [--latest, <version>]'. See 'cosm --help'. \n \n"
             exit 1
-            ;;
-    esac
+        fi
+    else
+        printf "ArgumentError: the signature is 'cosm add <package name> [--latest, <version>]'. See 'cosm --help'. \n \n"
+        exit 1
+    fi
 }
 
 upgrade(){
-    case $2 in
-        --latest)
-            lua $COSM_DIR/cli/cmd-upgrade-latest.lua $PWD "${1}" "${@:3}"
-            ;;
-        --version|-v)
-            lua $COSM_DIR/cli/cmd-upgrade-version.lua $PWD "${1}" "${@:3}"
-            ;;
-        *)
-            printf "ArgumentError: the signature is 'cosm upgrade <package name> [--latest, --version <version>]'. See 'cosm --help'. \n \n"
+    if [ "$#" -eq 2 ]; then
+        option="${2}"
+        if [ "${option}" == "--latest" ]; then
+            lua $COSM_DIR/cli/cmd-upgrade-latest.lua $PWD "${1}"
+        elif [ "${option:0:1}" == "v" ]; then
+            lua $COSM_DIR/cli/cmd-upgrade-version.lua $PWD "${1}" "${option:1}"
+        else
+            printf "ArgumentError: the signature is 'cosm upgrade <package name> [--latest, v<version>]'. See 'cosm --help'. \n \n"
             exit 1
-            ;;
-    esac
+        fi
+    else
+        printf "ArgumentError: the signature is 'cosm upgrade <package name> [--latest, v<version>]'. See 'cosm --help'. \n \n"
+        exit 1
+    fi
 }
 
 downgrade(){
-    case $2 in
-        --version|-v)
-            lua $COSM_DIR/cli/cmd-downgrade.lua $PWD "${1}" "${@:3}"
-            ;;
-        *)
-            printf "ArgumentError: the signature is 'cosm downgrade <package name> --version <version>'. See 'cosm --help'. \n \n"
+    if [ "$#" -eq 2 ]; then
+        option="${2}"
+        if [ "${option:0:1}" == "v" ]; then
+            lua $COSM_DIR/cli/cmd-downgrade.lua $PWD "${1}" "${option:1}"
+        else
+            printf "ArgumentError: the signature is 'cosm downgrade <package name> v<version>'. See 'cosm --help'. \n \n"
             exit 1
-            ;;
-    esac
+        fi
+    else
+        printf "ArgumentError: the signature is 'cosm downgrade <package name> v<version>'. See 'cosm --help'. \n \n"
+        exit 1
+    fi
+}
+
+remove(){
+    if [ "$#" -eq 1 ]; then
+        lua $COSM_DIR/cli/cmd-rm.lua $PWD "${1}"
+    else
+        printf "ArgumentError: the signature is 'cosm rm <package name>'. See 'cosm --help'. \n \n"
+        exit 1
+    fi
 }
 
 registry_delete(){
@@ -218,7 +234,7 @@ case "$1" in
     # Evaluate in root directory of a package. Remove a dependency from a project with <name>
     rm)
         checkname $2
-        lua $COSM_DIR/cli/cmd-rm.lua $PWD "${@:2}"
+        remove "${@:2}"
         ;;
 
     # Evaluate in root directory of a package. Upgrade a project dependency with <name> to <version>
